version: '3'

services:
  nginx:
    container_name: api-nginx
    image: nginx:1.20.2
    restart: always
    volumes:
      - ./backend-core:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/templates
    depends_on:
      - php
    links:
      - php
    ports:
      - "${COMPOSE_NGINX_PORT}:80"

  php:
    container_name: api-php
    build:
      context: ./docker/images/php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend-core:/var/www/html
      - ./docker/images/php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/images/php/supervisor:/etc/supervisor/conf.d
    links:
      - mysql

  mysql:
    container_name: api-mysql
    image: mysql:8
    restart: always
    volumes:
      - ./docker/db/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${COMPOSE_MYSQL_PORT}:3306"
  mysql-slave:
    container_name: api-mysql-slave
    image: mysql:8
    restart: always
    volumes:
      - ./docker/db/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD-SLAVE}"
      MYSQL_DATABASE: "${DB_DATABASE-SLAVE}"
      MYSQL_USER: "${DB_USERNAME-SLAVE}"
      MYSQL_PASSWORD: "${DB_PASSWORD-SLAVE}"
    ports:
      - "${COMPOSE_MYSQL_PORT-SLAVE}:3308"